# Generated by Django 4.0.2 on 2022-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kani',
            name='razbor',
            field=models.TextField(blank=True, verbose_name='разбор'),
        ),
    ]
